kind: Secret
apiVersion: v1
metadata:
  name: microfrontend-user-customer-requests
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/dev/automatix/microfrontend-user-customer-requests"
data:
type: Opaque
